/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface InstallationFacetInterface extends ethers.utils.Interface {
  functions: {
    "addInstallationTypes(tuple[])": FunctionFragment;
    "balanceOf(address,uint256)": FunctionFragment;
    "balanceOfBatch(address[],uint256[])": FunctionFragment;
    "balanceOfToken(address,uint256,uint256)": FunctionFragment;
    "claimInstallation(uint256)": FunctionFragment;
    "craftInstallations(uint256[])": FunctionFragment;
    "getInstallationType(uint256)": FunctionFragment;
    "getInstallationTypes(uint256[])": FunctionFragment;
    "itemBalances(address)": FunctionFragment;
    "itemBalancesOfToken(address,uint256)": FunctionFragment;
    "itemBalancesOfTokenWithTypes(address,uint256)": FunctionFragment;
    "itemBalancesWithTypes(address)": FunctionFragment;
    "setBaseURI(string)": FunctionFragment;
    "updateInstallationType((uint16,uint16,uint256,uint256,uint16,uint256[],uint256))": FunctionFragment;
    "uri(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addInstallationTypes",
    values: [
      {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfToken",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimInstallation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "craftInstallations",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstallationType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInstallationTypes",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "itemBalances",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "itemBalancesOfToken",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "itemBalancesOfTokenWithTypes",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "itemBalancesWithTypes",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "setBaseURI", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateInstallationType",
    values: [
      {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "addInstallationTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimInstallation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "craftInstallations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstallationType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInstallationTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "itemBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "itemBalancesOfToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "itemBalancesOfTokenWithTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "itemBalancesWithTypes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBaseURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateInstallationType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;

  events: {
    "TransferToParent(address,uint256,uint256,uint256)": EventFragment;
    "UseConsumables(uint256,uint256[],uint256[])": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TransferToParent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UseConsumables"): EventFragment;
}

export type TransferToParentEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber] & {
    _toContract: string;
    _toTokenId: BigNumber;
    _tokenTypeId: BigNumber;
    _value: BigNumber;
  }
>;

export type UseConsumablesEvent = TypedEvent<
  [BigNumber, BigNumber[], BigNumber[]] & {
    _tokenId: BigNumber;
    _itemIds: BigNumber[];
    _quantities: BigNumber[];
  }
>;

export class InstallationFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: InstallationFacetInterface;

  functions: {
    addInstallationTypes(
      _installationTypes: {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    balanceOf(
      _owner: string,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { bal_: BigNumber }>;

    balanceOfBatch(
      _owners: string[],
      _ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { bals: BigNumber[] }>;

    balanceOfToken(
      _tokenContract: string,
      _tokenId: BigNumberish,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { value: BigNumber }>;

    claimInstallation(
      _queueId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    craftInstallations(
      _installationTypes: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getInstallationType(
      _itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          number,
          number,
          BigNumber,
          BigNumber,
          number,
          BigNumber[],
          BigNumber
        ] & {
          installationType: number;
          level: number;
          width: BigNumber;
          height: BigNumber;
          alchemicaType: number;
          alchemicaCost: BigNumber[];
          craftTime: BigNumber;
        }
      ] & {
        installationType: [
          number,
          number,
          BigNumber,
          BigNumber,
          number,
          BigNumber[],
          BigNumber
        ] & {
          installationType: number;
          level: number;
          width: BigNumber;
          height: BigNumber;
          alchemicaType: number;
          alchemicaCost: BigNumber[];
          craftTime: BigNumber;
        };
      }
    >;

    getInstallationTypes(
      _itemIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          number,
          number,
          BigNumber,
          BigNumber,
          number,
          BigNumber[],
          BigNumber
        ] & {
          installationType: number;
          level: number;
          width: BigNumber;
          height: BigNumber;
          alchemicaType: number;
          alchemicaCost: BigNumber[];
          craftTime: BigNumber;
        })[]
      ] & {
        itemTypes_: ([
          number,
          number,
          BigNumber,
          BigNumber,
          number,
          BigNumber[],
          BigNumber
        ] & {
          installationType: number;
          level: number;
          width: BigNumber;
          height: BigNumber;
          alchemicaType: number;
          alchemicaCost: BigNumber[];
          craftTime: BigNumber;
        })[];
      }
    >;

    itemBalances(
      _account: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([BigNumber, BigNumber] & { itemId: BigNumber; balance: BigNumber })[]
      ] & {
        bals_: ([BigNumber, BigNumber] & {
          itemId: BigNumber;
          balance: BigNumber;
        })[];
      }
    >;

    itemBalancesOfToken(
      _tokenContract: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([BigNumber, BigNumber] & { itemId: BigNumber; balance: BigNumber })[]
      ] & {
        bals_: ([BigNumber, BigNumber] & {
          itemId: BigNumber;
          balance: BigNumber;
        })[];
      }
    >;

    itemBalancesOfTokenWithTypes(
      _tokenContract: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          BigNumber,
          BigNumber,
          [
            number,
            number,
            BigNumber,
            BigNumber,
            number,
            BigNumber[],
            BigNumber
          ] & {
            installationType: number;
            level: number;
            width: BigNumber;
            height: BigNumber;
            alchemicaType: number;
            alchemicaCost: BigNumber[];
            craftTime: BigNumber;
          }
        ] & {
          balance: BigNumber;
          itemId: BigNumber;
          installationType: [
            number,
            number,
            BigNumber,
            BigNumber,
            number,
            BigNumber[],
            BigNumber
          ] & {
            installationType: number;
            level: number;
            width: BigNumber;
            height: BigNumber;
            alchemicaType: number;
            alchemicaCost: BigNumber[];
            craftTime: BigNumber;
          };
        })[]
      ] & {
        itemBalancesOfTokenWithTypes_: ([
          BigNumber,
          BigNumber,
          [
            number,
            number,
            BigNumber,
            BigNumber,
            number,
            BigNumber[],
            BigNumber
          ] & {
            installationType: number;
            level: number;
            width: BigNumber;
            height: BigNumber;
            alchemicaType: number;
            alchemicaCost: BigNumber[];
            craftTime: BigNumber;
          }
        ] & {
          balance: BigNumber;
          itemId: BigNumber;
          installationType: [
            number,
            number,
            BigNumber,
            BigNumber,
            number,
            BigNumber[],
            BigNumber
          ] & {
            installationType: number;
            level: number;
            width: BigNumber;
            height: BigNumber;
            alchemicaType: number;
            alchemicaCost: BigNumber[];
            craftTime: BigNumber;
          };
        })[];
      }
    >;

    itemBalancesWithTypes(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          BigNumber,
          BigNumber,
          [
            number,
            number,
            BigNumber,
            BigNumber,
            number,
            BigNumber[],
            BigNumber
          ] & {
            installationType: number;
            level: number;
            width: BigNumber;
            height: BigNumber;
            alchemicaType: number;
            alchemicaCost: BigNumber[];
            craftTime: BigNumber;
          }
        ] & {
          balance: BigNumber;
          itemId: BigNumber;
          installationType: [
            number,
            number,
            BigNumber,
            BigNumber,
            number,
            BigNumber[],
            BigNumber
          ] & {
            installationType: number;
            level: number;
            width: BigNumber;
            height: BigNumber;
            alchemicaType: number;
            alchemicaCost: BigNumber[];
            craftTime: BigNumber;
          };
        })[]
      ] & {
        output_: ([
          BigNumber,
          BigNumber,
          [
            number,
            number,
            BigNumber,
            BigNumber,
            number,
            BigNumber[],
            BigNumber
          ] & {
            installationType: number;
            level: number;
            width: BigNumber;
            height: BigNumber;
            alchemicaType: number;
            alchemicaCost: BigNumber[];
            craftTime: BigNumber;
          }
        ] & {
          balance: BigNumber;
          itemId: BigNumber;
          installationType: [
            number,
            number,
            BigNumber,
            BigNumber,
            number,
            BigNumber[],
            BigNumber
          ] & {
            installationType: number;
            level: number;
            width: BigNumber;
            height: BigNumber;
            alchemicaType: number;
            alchemicaCost: BigNumber[];
            craftTime: BigNumber;
          };
        })[];
      }
    >;

    setBaseURI(
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateInstallationType(
      _updatedInstallation: {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uri(_id: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  addInstallationTypes(
    _installationTypes: {
      installationType: BigNumberish;
      level: BigNumberish;
      width: BigNumberish;
      height: BigNumberish;
      alchemicaType: BigNumberish;
      alchemicaCost: BigNumberish[];
      craftTime: BigNumberish;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  balanceOf(
    _owner: string,
    _id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balanceOfBatch(
    _owners: string[],
    _ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  balanceOfToken(
    _tokenContract: string,
    _tokenId: BigNumberish,
    _id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  claimInstallation(
    _queueId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  craftInstallations(
    _installationTypes: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getInstallationType(
    _itemId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [number, number, BigNumber, BigNumber, number, BigNumber[], BigNumber] & {
      installationType: number;
      level: number;
      width: BigNumber;
      height: BigNumber;
      alchemicaType: number;
      alchemicaCost: BigNumber[];
      craftTime: BigNumber;
    }
  >;

  getInstallationTypes(
    _itemIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([number, number, BigNumber, BigNumber, number, BigNumber[], BigNumber] & {
      installationType: number;
      level: number;
      width: BigNumber;
      height: BigNumber;
      alchemicaType: number;
      alchemicaCost: BigNumber[];
      craftTime: BigNumber;
    })[]
  >;

  itemBalances(
    _account: string,
    overrides?: CallOverrides
  ): Promise<
    ([BigNumber, BigNumber] & { itemId: BigNumber; balance: BigNumber })[]
  >;

  itemBalancesOfToken(
    _tokenContract: string,
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([BigNumber, BigNumber] & { itemId: BigNumber; balance: BigNumber })[]
  >;

  itemBalancesOfTokenWithTypes(
    _tokenContract: string,
    _tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      BigNumber,
      BigNumber,
      [number, number, BigNumber, BigNumber, number, BigNumber[], BigNumber] & {
        installationType: number;
        level: number;
        width: BigNumber;
        height: BigNumber;
        alchemicaType: number;
        alchemicaCost: BigNumber[];
        craftTime: BigNumber;
      }
    ] & {
      balance: BigNumber;
      itemId: BigNumber;
      installationType: [
        number,
        number,
        BigNumber,
        BigNumber,
        number,
        BigNumber[],
        BigNumber
      ] & {
        installationType: number;
        level: number;
        width: BigNumber;
        height: BigNumber;
        alchemicaType: number;
        alchemicaCost: BigNumber[];
        craftTime: BigNumber;
      };
    })[]
  >;

  itemBalancesWithTypes(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<
    ([
      BigNumber,
      BigNumber,
      [number, number, BigNumber, BigNumber, number, BigNumber[], BigNumber] & {
        installationType: number;
        level: number;
        width: BigNumber;
        height: BigNumber;
        alchemicaType: number;
        alchemicaCost: BigNumber[];
        craftTime: BigNumber;
      }
    ] & {
      balance: BigNumber;
      itemId: BigNumber;
      installationType: [
        number,
        number,
        BigNumber,
        BigNumber,
        number,
        BigNumber[],
        BigNumber
      ] & {
        installationType: number;
        level: number;
        width: BigNumber;
        height: BigNumber;
        alchemicaType: number;
        alchemicaCost: BigNumber[];
        craftTime: BigNumber;
      };
    })[]
  >;

  setBaseURI(
    _value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateInstallationType(
    _updatedInstallation: {
      installationType: BigNumberish;
      level: BigNumberish;
      width: BigNumberish;
      height: BigNumberish;
      alchemicaType: BigNumberish;
      alchemicaCost: BigNumberish[];
      craftTime: BigNumberish;
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uri(_id: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addInstallationTypes(
      _installationTypes: {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(
      _owner: string,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      _owners: string[],
      _ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    balanceOfToken(
      _tokenContract: string,
      _tokenId: BigNumberish,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimInstallation(
      _queueId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    craftInstallations(
      _installationTypes: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    getInstallationType(
      _itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [number, number, BigNumber, BigNumber, number, BigNumber[], BigNumber] & {
        installationType: number;
        level: number;
        width: BigNumber;
        height: BigNumber;
        alchemicaType: number;
        alchemicaCost: BigNumber[];
        craftTime: BigNumber;
      }
    >;

    getInstallationTypes(
      _itemIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([
        number,
        number,
        BigNumber,
        BigNumber,
        number,
        BigNumber[],
        BigNumber
      ] & {
        installationType: number;
        level: number;
        width: BigNumber;
        height: BigNumber;
        alchemicaType: number;
        alchemicaCost: BigNumber[];
        craftTime: BigNumber;
      })[]
    >;

    itemBalances(
      _account: string,
      overrides?: CallOverrides
    ): Promise<
      ([BigNumber, BigNumber] & { itemId: BigNumber; balance: BigNumber })[]
    >;

    itemBalancesOfToken(
      _tokenContract: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([BigNumber, BigNumber] & { itemId: BigNumber; balance: BigNumber })[]
    >;

    itemBalancesOfTokenWithTypes(
      _tokenContract: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        BigNumber,
        BigNumber,
        [
          number,
          number,
          BigNumber,
          BigNumber,
          number,
          BigNumber[],
          BigNumber
        ] & {
          installationType: number;
          level: number;
          width: BigNumber;
          height: BigNumber;
          alchemicaType: number;
          alchemicaCost: BigNumber[];
          craftTime: BigNumber;
        }
      ] & {
        balance: BigNumber;
        itemId: BigNumber;
        installationType: [
          number,
          number,
          BigNumber,
          BigNumber,
          number,
          BigNumber[],
          BigNumber
        ] & {
          installationType: number;
          level: number;
          width: BigNumber;
          height: BigNumber;
          alchemicaType: number;
          alchemicaCost: BigNumber[];
          craftTime: BigNumber;
        };
      })[]
    >;

    itemBalancesWithTypes(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<
      ([
        BigNumber,
        BigNumber,
        [
          number,
          number,
          BigNumber,
          BigNumber,
          number,
          BigNumber[],
          BigNumber
        ] & {
          installationType: number;
          level: number;
          width: BigNumber;
          height: BigNumber;
          alchemicaType: number;
          alchemicaCost: BigNumber[];
          craftTime: BigNumber;
        }
      ] & {
        balance: BigNumber;
        itemId: BigNumber;
        installationType: [
          number,
          number,
          BigNumber,
          BigNumber,
          number,
          BigNumber[],
          BigNumber
        ] & {
          installationType: number;
          level: number;
          width: BigNumber;
          height: BigNumber;
          alchemicaType: number;
          alchemicaCost: BigNumber[];
          craftTime: BigNumber;
        };
      })[]
    >;

    setBaseURI(_value: string, overrides?: CallOverrides): Promise<void>;

    updateInstallationType(
      _updatedInstallation: {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    uri(_id: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "TransferToParent(address,uint256,uint256,uint256)"(
      _toContract?: string | null,
      _toTokenId?: BigNumberish | null,
      _tokenTypeId?: BigNumberish | null,
      _value?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        _toContract: string;
        _toTokenId: BigNumber;
        _tokenTypeId: BigNumber;
        _value: BigNumber;
      }
    >;

    TransferToParent(
      _toContract?: string | null,
      _toTokenId?: BigNumberish | null,
      _tokenTypeId?: BigNumberish | null,
      _value?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        _toContract: string;
        _toTokenId: BigNumber;
        _tokenTypeId: BigNumber;
        _value: BigNumber;
      }
    >;

    "UseConsumables(uint256,uint256[],uint256[])"(
      _tokenId?: BigNumberish | null,
      _itemIds?: null,
      _quantities?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber[], BigNumber[]],
      { _tokenId: BigNumber; _itemIds: BigNumber[]; _quantities: BigNumber[] }
    >;

    UseConsumables(
      _tokenId?: BigNumberish | null,
      _itemIds?: null,
      _quantities?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber[], BigNumber[]],
      { _tokenId: BigNumber; _itemIds: BigNumber[]; _quantities: BigNumber[] }
    >;
  };

  estimateGas: {
    addInstallationTypes(
      _installationTypes: {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    balanceOf(
      _owner: string,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      _owners: string[],
      _ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfToken(
      _tokenContract: string,
      _tokenId: BigNumberish,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    claimInstallation(
      _queueId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    craftInstallations(
      _installationTypes: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getInstallationType(
      _itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getInstallationTypes(
      _itemIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    itemBalances(
      _account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    itemBalancesOfToken(
      _tokenContract: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    itemBalancesOfTokenWithTypes(
      _tokenContract: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    itemBalancesWithTypes(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBaseURI(
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateInstallationType(
      _updatedInstallation: {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uri(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addInstallationTypes(
      _installationTypes: {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    balanceOf(
      _owner: string,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOfBatch(
      _owners: string[],
      _ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOfToken(
      _tokenContract: string,
      _tokenId: BigNumberish,
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claimInstallation(
      _queueId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    craftInstallations(
      _installationTypes: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getInstallationType(
      _itemId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getInstallationTypes(
      _itemIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    itemBalances(
      _account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    itemBalancesOfToken(
      _tokenContract: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    itemBalancesOfTokenWithTypes(
      _tokenContract: string,
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    itemBalancesWithTypes(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBaseURI(
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateInstallationType(
      _updatedInstallation: {
        installationType: BigNumberish;
        level: BigNumberish;
        width: BigNumberish;
        height: BigNumberish;
        alchemicaType: BigNumberish;
        alchemicaCost: BigNumberish[];
        craftTime: BigNumberish;
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uri(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
